/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mr_zyl_project824_jniutils_MathKit */

#ifndef _Included_com_example_mr_zyl_project824_jniutils_MathKit
#define _Included_com_example_mr_zyl_project824_jniutils_MathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mr_zyl_project824_jniutils_MathKit
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_mr_1zyl_project824_jniutils_MathKit_square
        (JNIEnv *env, jclass cls, jint num){
    return num*num;
}

#ifdef __cplusplus
}
#endif
#endif
